import type { Metadata } from "next";
import { arabic, amiri, geist } from "@/config/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir="rtl"
      suppressHydrationWarning
      className={`
    ${geist.variable}
    ${arabic.variable}
    ${amiri.variable}
    h-full
    antialiased
  `}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
